version: '3.8'

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    hostname: mongo1
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db
      - ./tls:/etc/ssl/mongo:ro
    networks:
      - mongo-cluster
    command:
      [
        "mongod",
        "--replSet=rs0",
        "--bind_ip_all",
        "--tlsMode=requireTLS",
        "--tlsCertificateKeyFile=/etc/ssl/mongo/mongo1.pem",
        "--tlsCAFile=/etc/ssl/mongo/ca.crt"
      ]

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    hostname: mongo2
    ports:
      - 27018:27017
    volumes:
      - mongo2-data:/data/db
      - ./tls:/etc/ssl/mongo:ro
    networks:
      - mongo-cluster
    command:
      [
        "mongod",
        "--replSet=rs0",
        "--bind_ip_all",
        "--tlsMode=requireTLS",
        "--tlsCertificateKeyFile=/etc/ssl/mongo/mongo2.pem",
        "--tlsCAFile=/etc/ssl/mongo/ca.crt"
      ]

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    hostname: mongo3
    ports:
      - 27019:27017
    volumes:
      - mongo3-data:/data/db
      - ./tls:/etc/ssl/mongo:ro
    networks:
      - mongo-cluster
    command:
      [
        "mongod",
        "--replSet=rs0",
        "--bind_ip_all",
        "--tlsMode=requireTLS",
        "--tlsCertificateKeyFile=/etc/ssl/mongo/mongo3.pem",
        "--tlsCAFile=/etc/ssl/mongo/ca.crt"
      ]

    mongo-arbiter:
    image: mongo:6.0
    container_name: mongo-arbiter
    hostname: mongo-arbiter
    ports:
      - 27020:27017
    volumes:
      - mongo-arbiter-data:/data/db
      - ./tls:/etc/ssl/mongo:ro
    networks:
      - mongo-cluster
    command:
      [
        "mongod",
        "--replSet=rs0",
        "--bind_ip_all",
        "--tlsMode=requireTLS",
        "--tlsCertificateKeyFile=/etc/ssl/mongo/mongo-arbiter.pem",
        "--tlsCAFile=/etc/ssl/mongo/ca.crt"
      ]
    

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
  mongo-arbiter-data:


networks:
  mongo-cluster:
    driver: bridge
